version: "3"
services:
  hub:
    image: selenium/hub:latest
#    ports:
#      - "4442:4442"
#      - "4443:4443"
#      - "4444:4444"
  chrome:
    image: selenium/node-chrome:beta
    shm_size: '1g'

    depends_on:
      - hub
#    deploy:
#      replicas: 2
    env_file: .env

  edge:
    image: selenium/node-edge:beta
    shm_size: '1g'
    depends_on:
      - hub
#    deploy:
#      replicas: 2
    env_file: .env



