version: "3"
services:
  dockerimage:
    image: rajat725/dockerframework
    environment:
      - GRID=true
      - THREAD_COUNT=2
      - HUBURL=http://hub:4444
      - XMLFILE=testng.xml
    volumes:
      - ./output/results:/home/DockerFramework/test-output
      - ./test.log:/home/DockerFramework/test.log


